name: CI hello user bash

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hello bash script
        run: |
          #!/bin/bash
          echo "First Name: ${{ env.MYNAME }}"
          echo "Last Name: ${{ env.MYSURNAME }}"
